/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author luv
 */
public class ComplaintBox extends javax.swing.JFrame {

    /**
     * Creates new form ComplaintBox
     * @param userid
     */
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private static String userid;
    
    public ComplaintBox(String userid) {
        this.userid = userid;
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        tvUser.setText(userid);
        tvDate.setText(new SimpleDateFormat("yyyy-MM-dd").format( new Date() ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCancel = new javax.swing.JButton();
        btReport = new javax.swing.JButton();
        tvDate = new javax.swing.JTextField();
        tvUser = new javax.swing.JTextField();
        lDate = new javax.swing.JLabel();
        lUserId = new javax.swing.JLabel();
        lCategory = new javax.swing.JLabel();
        tvCategory = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        etComplaint = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "COMPLAINT", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        btCancel.setBackground(new java.awt.Color(0, 0, 102));
        btCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCancel.setForeground(new java.awt.Color(0, 0, 153));
        btCancel.setText("CANCEL");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        btReport.setBackground(new java.awt.Color(0, 0, 102));
        btReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btReport.setForeground(new java.awt.Color(0, 0, 102));
        btReport.setText("REPORT");
        btReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportActionPerformed(evt);
            }
        });

        tvDate.setBackground(new java.awt.Color(0, 0, 102));
        tvDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tvDate.setForeground(new java.awt.Color(255, 255, 255));
        tvDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvDate.setToolTipText("Book Barcode");
        tvDate.setEnabled(false);

        tvUser.setBackground(new java.awt.Color(0, 0, 102));
        tvUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tvUser.setForeground(new java.awt.Color(255, 255, 255));
        tvUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvUser.setToolTipText("Student Barcode");
        tvUser.setEnabled(false);

        lDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lDate.setForeground(new java.awt.Color(255, 255, 255));
        lDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDate.setText("DATE");
        lDate.setEnabled(false);

        lUserId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lUserId.setForeground(new java.awt.Color(255, 255, 255));
        lUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lUserId.setText("USER ID");
        lUserId.setEnabled(false);

        lCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lCategory.setForeground(new java.awt.Color(255, 255, 255));
        lCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCategory.setText("CATEGORY");
        lCategory.setEnabled(false);

        tvCategory.setBackground(new java.awt.Color(0, 0, 102));
        tvCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tvCategory.setForeground(new java.awt.Color(255, 255, 255));
        tvCategory.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvCategory.setToolTipText("Student Barcode");

        etComplaint.setColumns(20);
        etComplaint.setRows(5);
        etComplaint.setToolTipText("Enter Complaint");
        etComplaint.setWrapStyleWord(true);
        jScrollPane1.setViewportView(etComplaint);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btReport, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(lDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lUserId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tvDate, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tvUser)
                                    .addComponent(tvCategory))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUserId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tvCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lCategory))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btReport, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btCancelActionPerformed

    private void btReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportActionPerformed
        // TODO add your handling code here:

        try{
            if( tvCategory.getText() == null )
                JOptionPane.showMessageDialog( null, "Must enter category, e.g. Peon,Painter,Electrician,etc" );
            else if( etComplaint.getText() == null )
                JOptionPane.showMessageDialog( null, "No Complaint Entered" );
            else{
                String sql = "insert into form(doc,about,version) values('" + tvDate.getText() + "','" + etComplaint.getText() + "','complaint') ;";
                pst = conn.prepareStatement(sql);
                pst.execute();
                sql = "insert into docGenerated(u_id) values('" + tvUser.getText() + "') ;";
                pst = conn.prepareStatement(sql);
                pst.execute();
                sql = "insert into complaint(category) values('" + tvCategory.getText() + "') ;";
                pst = conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog( null, "Complaint successfully Registered" );
                tvCategory.setText(null);
                etComplaint.setText(null);
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }//GEN-LAST:event_btReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplaintBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplaintBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplaintBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplaintBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplaintBox(userid).setVisible(true);
            }
        });
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btReport;
    private javax.swing.JTextArea etComplaint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCategory;
    private javax.swing.JLabel lDate;
    private javax.swing.JLabel lUserId;
    private javax.swing.JTextField tvCategory;
    private javax.swing.JTextField tvDate;
    private javax.swing.JTextField tvUser;
    // End of variables declaration//GEN-END:variables
}
