/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LUV
 */
public class Details extends javax.swing.JFrame {

    private static String userID;
    private static String Command;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form EditBooks
     * @param userID
     */
    public Details(String userID) {
        this.userID = userID;
        Command = "EDIT";
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        DisplayData();
        Button.setText(Command);
        fillCombos();
    }

    private void fillCombos(){
        try{
            
            String sql = "select contact from phone where u_id = '" + userID + "';";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            cbPhone.removeAllItems();
            while( rs.next() )
                cbPhone.addItem(rs.getString("contact"));
            
            sql = "select sub_name from subjects where sub_id in ( select sub_id from courseSubjects where course_id = '" + tvCourse.getText() + "' and sem_no = '" + Integer.parseInt(cbSemester.getSelectedItem().toString()) + "');";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            cbSubjects.removeAllItems();
            while( rs.next() )
                cbSubjects.addItem(rs.getString("sub_name"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    private void DisplayData(){
        try{
            String sql = " select user.*,student.percentage from user,student where user.u_id = '"+userID+"' and user.u_id = student.u_id;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            if( rs.next() ){
                tvuserid.setText( rs.getString("u_id") );
                tvfname.setText( rs.getString("fname") );
                tvmname.setText( rs.getString("mname") );
                tvlname.setText( rs.getString("lname") );
                tvAddress.setText( rs.getString("address") );
                tvSex.setText( rs.getString("sex") );
                tvDob.setText( rs.getString("dob") );
                etPercentage.setText( rs.getString("percentage") );
            }
            
            sql = " select course_id from courseEnrolments where u_id = '" + userID + "';";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            if( rs.next() ){
                tvCourse.setText( rs.getString("course_id") );
            }
            
            sql = " select dept_name from department where dept_id = ( select dept_id from belongsTo where u_id = '" + userID + "');";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            if( rs.next() ){    
                etDepartment.setText( rs.getString("dept_name") );
            }   
                
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etPercentage = new javax.swing.JTextField();
        userid = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        tvCourse = new javax.swing.JTextField();
        lname = new javax.swing.JLabel();
        tvAddress = new javax.swing.JTextField();
        subjects = new javax.swing.JLabel();
        tvlname = new javax.swing.JTextField();
        Phone = new javax.swing.JLabel();
        course = new javax.swing.JLabel();
        etDepartment = new javax.swing.JTextField();
        department = new javax.swing.JLabel();
        tvSex = new javax.swing.JTextField();
        fname = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();
        tvfname = new javax.swing.JTextField();
        semester = new javax.swing.JLabel();
        tvDob = new javax.swing.JTextField();
        tvuserid = new javax.swing.JTextField();
        mname = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        tvmname = new javax.swing.JTextField();
        cbSemester = new javax.swing.JComboBox();
        cbPhone = new javax.swing.JComboBox();
        cbSubjects = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        etPercentage.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        etPercentage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etPercentage.setEnabled(false);

        userid.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        userid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userid.setText("USER ID");

        Address.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Address.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Address.setText("ADDRESS");

        tvCourse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvCourse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvCourse.setEnabled(false);

        lname.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        lname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lname.setText("LAST NAME");

        tvAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvAddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvAddress.setEnabled(false);

        subjects.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        subjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjects.setText("SUBJECTS");

        tvlname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvlname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvlname.setEnabled(false);
        tvlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvlnameActionPerformed(evt);
            }
        });

        Phone.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Phone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Phone.setText("PHONE");

        course.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        course.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        course.setText("COURSE");

        etDepartment.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        etDepartment.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etDepartment.setEnabled(false);

        department.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        department.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        department.setText("DEPARTMENT");

        tvSex.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvSex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvSex.setEnabled(false);

        fname.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        fname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fname.setText("FIRST NAME");

        Sex.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Sex.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sex.setText("SEX");

        percentage.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        percentage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentage.setText("PERCENTAGE");

        tvfname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvfname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvfname.setEnabled(false);

        semester.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        semester.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        semester.setText("SEMESTER");

        tvDob.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvDob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvDob.setEnabled(false);
        tvDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvDobActionPerformed(evt);
            }
        });

        tvuserid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvuserid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvuserid.setEnabled(false);

        mname.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        mname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mname.setText("MIDDLE NAME");

        dob.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dob.setText("DATE OF BIRTH");

        tvmname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvmname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tvmname.setEnabled(false);
        tvmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvmnameActionPerformed(evt);
            }
        });

        cbSemester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        cbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSemesterActionPerformed(evt);
            }
        });

        cbPhone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbSubjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(department, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subjects, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(course, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(Phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(semester, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tvCourse)
                    .addComponent(etPercentage)
                    .addComponent(etDepartment)
                    .addComponent(tvDob)
                    .addComponent(tvSex)
                    .addComponent(tvAddress)
                    .addComponent(tvlname)
                    .addComponent(tvuserid)
                    .addComponent(tvfname)
                    .addComponent(tvmname)
                    .addComponent(cbSemester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbPhone, 0, 500, Short.MAX_VALUE)
                    .addComponent(cbSubjects, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvuserid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvfname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvmname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvlname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvSex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvDob))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvCourse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjects, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etDepartment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etPercentage))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        Button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Button.setText("EDIT");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvDobActionPerformed

    private void tvmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvmnameActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void tvlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvlnameActionPerformed

    private String EditQuery(){
        return "update user set u_id ='" + tvuserid.getText() + "' ,"
                    + "fname='" + tvfname.getText() + "' ,"
                    + "mname='" + tvmname.getText() + "' ,"
                    + "lname='" + tvlname.getText() + "' ,"
                    + "address='" + tvAddress.getText() + "' ,"
                    + "sex='" + tvSex.getText() + "' ,"
                    + "dob='" + tvDob.getText() + "' "
                    + "where u_id='"+ userID +"';";
    }

   
    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            if( Button.getText().equals("EDIT") ){
                tvuserid.setEnabled(true);
                tvfname.setEnabled(true);
                tvmname.setEnabled(true);
                tvlname.setEnabled(true);
                tvAddress.setEnabled(true);
                tvSex.setEnabled(true);
                tvDob.setEnabled(true);
                Button.setText("SAVE");
            } else if( Button.getText().equals("SAVE") ){
                String sql = EditQuery();
                pst = conn.prepareStatement(sql);
                pst.execute();
                userID = tvuserid.getText();
                tvuserid.setEnabled(false);
                tvfname.setEnabled(false);
                tvmname.setEnabled(false);
                tvlname.setEnabled(false);
                tvAddress.setEnabled(false);
                tvSex.setEnabled(false);
                tvDob.setEnabled(false);
                Button.setText("EDIT");
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }//GEN-LAST:event_ButtonActionPerformed

    private void cbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSemesterActionPerformed
        // TODO add your handling code here:
        try{
            
            String sql = "select sub_name from subjects where sub_id in ( select sub_id from courseSubjects where course_id = '" + tvCourse.getText() + "' and sem_no = '" + Integer.parseInt(cbSemester.getSelectedItem().toString()) + "');";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            cbSubjects.removeAllItems();
            while( rs.next() )
                cbSubjects.addItem(rs.getString("sub_name"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }//GEN-LAST:event_cbSemesterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details( userID ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JButton Button;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Sex;
    private javax.swing.JComboBox cbPhone;
    private javax.swing.JComboBox cbSemester;
    private javax.swing.JComboBox cbSubjects;
    private javax.swing.JLabel course;
    private javax.swing.JLabel department;
    private javax.swing.JLabel dob;
    private javax.swing.JTextField etDepartment;
    private javax.swing.JTextField etPercentage;
    private javax.swing.JLabel fname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel mname;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel semester;
    private javax.swing.JLabel subjects;
    private javax.swing.JTextField tvAddress;
    private javax.swing.JTextField tvCourse;
    private javax.swing.JTextField tvDob;
    private javax.swing.JTextField tvSex;
    private javax.swing.JTextField tvfname;
    private javax.swing.JTextField tvlname;
    private javax.swing.JTextField tvmname;
    private javax.swing.JTextField tvuserid;
    private javax.swing.JLabel userid;
    // End of variables declaration//GEN-END:variables
}
