/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LUV
 */
public class FindJournalMagazine extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form FindJournalMagazine
     */
    public FindJournalMagazine() {
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        fillCombos();
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void fillCombos(){
        try{
            String sql = "select sub_name from subjects;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            while( rs.next() )
                cbSubjects.addItem(rs.getString("sub_name"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        FindID = new javax.swing.JButton();
        etID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        FindTitle = new javax.swing.JButton();
        etTitle = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        FindVendor = new javax.swing.JButton();
        etAuthor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        FindPublisher = new javax.swing.JButton();
        etPublisher = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        FindReceiptDate = new javax.swing.JButton();
        etDate = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        FindPeriodicity = new javax.swing.JButton();
        cbSubjects = new javax.swing.JComboBox();
        CancelButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        FindID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindID.setText("FIND");
        FindID.setEnabled(false);
        FindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindIDActionPerformed(evt);
            }
        });

        etID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        etID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etIDKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etID, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(FindID, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(etID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(FindID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ACCESSION ID", jPanel1);

        FindTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindTitle.setText("FIND");
        FindTitle.setEnabled(false);
        FindTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindTitleActionPerformed(evt);
            }
        });

        etTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etTitleKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(FindTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(etTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(FindTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TITLE", jPanel2);

        FindVendor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindVendor.setText("FIND");
        FindVendor.setEnabled(false);
        FindVendor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindVendorActionPerformed(evt);
            }
        });

        etAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etAuthor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etAuthor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etAuthor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etAuthorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(FindVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(etAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(FindVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AUTHOR", jPanel3);

        FindPublisher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindPublisher.setText("FIND");
        FindPublisher.setEnabled(false);
        FindPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPublisherActionPerformed(evt);
            }
        });

        etPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etPublisher.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etPublisher.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etPublisher.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etPublisherKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(FindPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(etPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(FindPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PUBLISHER", jPanel4);

        FindReceiptDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindReceiptDate.setText("FIND");
        FindReceiptDate.setEnabled(false);
        FindReceiptDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindReceiptDateActionPerformed(evt);
            }
        });

        etDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        etDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        etDate.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        etDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                etDateKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etDate, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(FindReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(etDate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(FindReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DATE", jPanel5);

        FindPeriodicity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindPeriodicity.setText("FIND");
        FindPeriodicity.setEnabled(false);
        FindPeriodicity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPeriodicityActionPerformed(evt);
            }
        });

        cbSubjects.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSubjects, 0, 504, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(FindPeriodicity, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(cbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(FindPeriodicity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("SUBJECTS", jPanel6);

        CancelButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelButton1.setText("CANCEL");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_CancelButton1ActionPerformed

    private void cbSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectsActionPerformed
        // TODO add your handling code here:
        FindPeriodicity.setEnabled(true);
    }//GEN-LAST:event_cbSubjectsActionPerformed

    private void FindPeriodicityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPeriodicityActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "select sub_id from subjects where sub_name = '" + cbSubjects.getSelectedItem().toString() + "';";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            if( rs.next() )
                librarianHome.value = rs.getString("sub_id");

            librarianHome.column = "sub_id";
            close();
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }//GEN-LAST:event_FindPeriodicityActionPerformed

    private void FindReceiptDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindReceiptDateActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "doa";
        librarianHome.value = etDate.getText();
        close();
    }//GEN-LAST:event_FindReceiptDateActionPerformed

    private void FindPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPublisherActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "publication";
        librarianHome.value = etPublisher.getText();
        close();
    }//GEN-LAST:event_FindPublisherActionPerformed

    private void FindVendorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindVendorActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "author";
        librarianHome.value = etAuthor.getText();
        close();
    }//GEN-LAST:event_FindVendorActionPerformed

    private void etTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etTitleKeyTyped
        // TODO add your handling code here:
        FindTitle.setEnabled(true);
    }//GEN-LAST:event_etTitleKeyTyped

    private void FindTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindTitleActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "bibname";
        librarianHome.value = etTitle.getText().toUpperCase();
        close();
    }//GEN-LAST:event_FindTitleActionPerformed

    private void etIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etIDKeyTyped
        // TODO add your handling code here:
        FindID.setEnabled(true);
    }//GEN-LAST:event_etIDKeyTyped

    private void FindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindIDActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "acc_id";
        librarianHome.value = etID.getText().toUpperCase();
        close();
    }//GEN-LAST:event_FindIDActionPerformed

    private void ReceiptDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiptDateMouseClicked
        // TODO add your handling code here:
        FindReceiptDate.setEnabled(true);
    }//GEN-LAST:event_ReceiptDateMouseClicked

    private void etAuthorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etAuthorKeyTyped
        // TODO add your handling code here:
        FindVendor.setEnabled(true);
    }//GEN-LAST:event_etAuthorKeyTyped

    private void etPublisherKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etPublisherKeyTyped
        // TODO add your handling code here:
        FindPublisher.setEnabled(true);
    }//GEN-LAST:event_etPublisherKeyTyped

    private void etDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_etDateKeyTyped
        // TODO add your handling code here:
        FindReceiptDate.setEnabled(true);
    }//GEN-LAST:event_etDateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindJournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindJournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindJournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindJournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindJournalMagazine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton FindID;
    private javax.swing.JButton FindPeriodicity;
    private javax.swing.JButton FindPublisher;
    private javax.swing.JButton FindReceiptDate;
    private javax.swing.JButton FindTitle;
    private javax.swing.JButton FindVendor;
    private javax.swing.JComboBox cbSubjects;
    private javax.swing.JTextField etAuthor;
    private javax.swing.JTextField etDate;
    private javax.swing.JTextField etID;
    private javax.swing.JTextField etPublisher;
    private javax.swing.JTextField etTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
