/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LUV
 */
public class FindBooks extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form FindBooks
     */
    public FindBooks() {
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        fillCombos();
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void fillCombos(){
        try{
            String sql = "select Name from Authors;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            while( rs.next() )
                AuthorCombo.addItem(rs.getString("Name"));
            
            sql = "select Name from Publisher;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            while( rs.next() )
                PublisherCombo.addItem(rs.getString("Name"));
            
            sql = "select Subject from Course;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            while( rs.next() )
                CourseCombo.addItem(rs.getString("Subject"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        FindID = new javax.swing.JButton();
        IDLabel = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        FindTitle = new javax.swing.JButton();
        TitleText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        FindAuthor = new javax.swing.JButton();
        AuthorCombo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        FindPublisher = new javax.swing.JButton();
        PublisherCombo = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        FindBillNo = new javax.swing.JButton();
        BillNoText = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        FindCourse = new javax.swing.JButton();
        CourseCombo = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        ScanBarcode = new javax.swing.JButton();
        BarcodeText = new javax.swing.JTextField();
        FindBarcode = new javax.swing.JButton();
        CancelButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        FindID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindID.setText("FIND");
        FindID.setEnabled(false);
        FindID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindIDActionPerformed(evt);
            }
        });

        IDLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel.setText("ID");

        IDText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        IDText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IDText, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                    .addComponent(FindID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(FindID, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ACCESSION ID", jPanel1);

        FindTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindTitle.setText("FIND");
        FindTitle.setEnabled(false);
        FindTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindTitleActionPerformed(evt);
            }
        });

        TitleText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TitleText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TitleText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TitleTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(TitleText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(TitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(FindTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TITLE", jPanel2);

        FindAuthor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindAuthor.setText("FIND");
        FindAuthor.setEnabled(false);
        FindAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindAuthorActionPerformed(evt);
            }
        });

        AuthorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(AuthorCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(AuthorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(FindAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("AUTHOR", jPanel3);

        FindPublisher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindPublisher.setText("FIND");
        FindPublisher.setEnabled(false);
        FindPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindPublisherActionPerformed(evt);
            }
        });

        PublisherCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PublisherCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublisherComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindPublisher, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(PublisherCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(PublisherCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(FindPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("PUBLISHER", jPanel4);

        FindBillNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindBillNo.setText("FIND");
        FindBillNo.setEnabled(false);
        FindBillNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBillNoActionPerformed(evt);
            }
        });

        BillNoText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BillNoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BillNoText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BillNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BillNoTextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindBillNo, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(BillNoText))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(BillNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(FindBillNo, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("BILL NO", jPanel5);

        FindCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindCourse.setText("FIND");
        FindCourse.setEnabled(false);
        FindCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindCourseActionPerformed(evt);
            }
        });

        CourseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CourseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FindCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(CourseCombo, 0, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(CourseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(FindCourse, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("COURSE", jPanel6);

        ScanBarcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ScanBarcode.setText("SCAN");
        ScanBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScanBarcodeActionPerformed(evt);
            }
        });

        BarcodeText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BarcodeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BarcodeText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BarcodeText.setEnabled(false);

        FindBarcode.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FindBarcode.setText("FIND");
        FindBarcode.setEnabled(false);
        FindBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBarcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BarcodeText, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(ScanBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FindBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BarcodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScanBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(FindBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("BARCODE", jPanel7);

        CancelButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CancelButton1.setText("CANCEL");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindIDActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "AccessionID";
        librarianHome.value = IDText.getText().toUpperCase();
        close();
    }//GEN-LAST:event_FindIDActionPerformed

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_CancelButton1ActionPerformed

    private void FindTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindTitleActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "Title";
        librarianHome.value = TitleText.getText().toUpperCase();
        close();
    }//GEN-LAST:event_FindTitleActionPerformed

    private void FindAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindAuthorActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "AuthorCode1";
        librarianHome.value = AuthorCombo.getSelectedItem().toString();
        close();
    }//GEN-LAST:event_FindAuthorActionPerformed

    private void ScanBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScanBarcodeActionPerformed
        // TODO add your handling code here:
        BarcodeText.setEnabled(true);
    }//GEN-LAST:event_ScanBarcodeActionPerformed

    private void FindCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindCourseActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "SubjectID";
        librarianHome.value = CourseCombo.getSelectedItem().toString();
        close();
    }//GEN-LAST:event_FindCourseActionPerformed

    private void FindBillNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBillNoActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "BillNo";
        librarianHome.value = BillNoText.getText();
        close();
    }//GEN-LAST:event_FindBillNoActionPerformed

    private void FindPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindPublisherActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "PublisherID";
        librarianHome.value = PublisherCombo.getSelectedItem().toString();
        close();
    }//GEN-LAST:event_FindPublisherActionPerformed

    private void PublisherComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublisherComboActionPerformed
        // TODO add your handling code here:
        FindPublisher.setEnabled(true);
    }//GEN-LAST:event_PublisherComboActionPerformed

    private void FindBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBarcodeActionPerformed
        // TODO add your handling code here:
        librarianHome.column = "BarCode";
        librarianHome.value = BarcodeText.getText();
        close();
    }//GEN-LAST:event_FindBarcodeActionPerformed

    private void IDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDTextKeyTyped
        // TODO add your handling code here:
        FindID.setEnabled(true);
    }//GEN-LAST:event_IDTextKeyTyped

    private void TitleTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TitleTextKeyTyped
        // TODO add your handling code here:
        FindTitle.setEnabled(true);
    }//GEN-LAST:event_TitleTextKeyTyped

    private void AuthorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorComboActionPerformed
        // TODO add your handling code here:
        FindAuthor.setEnabled(true);
    }//GEN-LAST:event_AuthorComboActionPerformed

    private void CourseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseComboActionPerformed
        // TODO add your handling code here:
        FindCourse.setEnabled(true);
    }//GEN-LAST:event_CourseComboActionPerformed

    private void BillNoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BillNoTextKeyTyped
        // TODO add your handling code here:
        FindBillNo.setEnabled(true);
    }//GEN-LAST:event_BillNoTextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AuthorCombo;
    private javax.swing.JTextField BarcodeText;
    private javax.swing.JTextField BillNoText;
    private javax.swing.JButton CancelButton1;
    private javax.swing.JComboBox CourseCombo;
    private javax.swing.JButton FindAuthor;
    private javax.swing.JButton FindBarcode;
    private javax.swing.JButton FindBillNo;
    private javax.swing.JButton FindCourse;
    private javax.swing.JButton FindID;
    private javax.swing.JButton FindPublisher;
    private javax.swing.JButton FindTitle;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JComboBox PublisherCombo;
    private javax.swing.JButton ScanBarcode;
    private javax.swing.JTextField TitleText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
