/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LUV
 */
public class JournalMagazine extends javax.swing.JFrame {

    private static String ID;
    private static String Command;
    private static String Type;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form JournalMagazine
     * @param id
     * @param command
     * @param type
     */
    public JournalMagazine( String id , String command , String type ) {
        ID = id;
        Command = command;
        Type = type;
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        if( Command.equals("EDIT") ){
            Button.setText("SAVE");
            DisplayData();
        }
        else if( Command.equals("ADD") )
            Button.setText("ADD");
        fillCombos();
    }

    private void fillCombos(){
        try{
            String sql = "select Name from Publisher;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            while( rs.next() )
                PublisherCombo.addItem(rs.getString("Name"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    private void DisplayData(){
        try{
            String sql = " select * from " + Type + " where ID = '" + ID + "';";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            if( rs.next() ){
                IDText.setText( rs.getString("ID") );
                TitleText.setText( rs.getString("Title") );
                PublisherCombo.setSelectedItem( rs.getString("PublisherID"));
                VendorText.setText( rs.getString("Vendor") );
                EditionText.setText( rs.getString("Edition") );
                PeriodicityCombo.setSelectedItem( rs.getString("Periodicity") );
                VolumeText.setText( rs.getString("Volume") );
                NumberText.setText( rs.getString("Number") );
                ReceiptDateText.setText( rs.getString("ReceiptDate") );
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ReceiptDateText = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        Vendor = new javax.swing.JLabel();
        VolumeText = new javax.swing.JTextField();
        VendorText = new javax.swing.JTextField();
        Number = new javax.swing.JLabel();
        Publisher = new javax.swing.JLabel();
        Volume = new javax.swing.JLabel();
        NumberText = new javax.swing.JTextField();
        Title = new javax.swing.JLabel();
        ReceiptDate = new javax.swing.JLabel();
        TitleText = new javax.swing.JTextField();
        Periodicity = new javax.swing.JLabel();
        EditionText = new javax.swing.JTextField();
        IDText = new javax.swing.JTextField();
        Edition = new javax.swing.JLabel();
        PeriodicityCombo = new javax.swing.JComboBox();
        PublisherCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ReceiptDateText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ReceiptDateText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        IDLabel.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        IDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel.setText("ID");

        Vendor.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Vendor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vendor.setText("VENDOR");

        VolumeText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VolumeText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        VendorText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VendorText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Number.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Number.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Number.setText("NUMBER");

        Publisher.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Publisher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Publisher.setText("PUBLISHER");

        Volume.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Volume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Volume.setText("VOLUME");

        NumberText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NumberText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Title.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("TITLE");

        ReceiptDate.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        ReceiptDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptDate.setText("DATE");

        TitleText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TitleText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Periodicity.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Periodicity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Periodicity.setText("PERIODICITY");

        EditionText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EditionText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EditionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditionTextActionPerformed(evt);
            }
        });

        IDText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IDText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Edition.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Edition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edition.setText("EDITION");

        PeriodicityCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "WEEKLY", "FORTNIGHTLY", "MONTHLY", "QUARTERLY", "BIANNUALY", "ANNUALY", " " }));

        PublisherCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ReceiptDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Volume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vendor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Edition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Publisher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Periodicity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VolumeText)
                    .addComponent(ReceiptDateText)
                    .addComponent(NumberText)
                    .addComponent(EditionText)
                    .addComponent(VendorText)
                    .addComponent(IDText)
                    .addComponent(TitleText)
                    .addComponent(PeriodicityCombo, 0, 500, Short.MAX_VALUE)
                    .addComponent(PublisherCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublisherCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VendorText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Periodicity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PeriodicityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edition, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditionText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Volume, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VolumeText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceiptDateText))
                .addContainerGap())
        );

        Button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditionTextActionPerformed

    private String EditQuery(){
        return "update " + Type + " set ID='" + IDText.getText() + "' ,"
                    + "Title='" + TitleText.getText() + "' ,"
                    + "PublisherID='" + PublisherCombo.getSelectedItem().toString() + "' ,"
                    + "Vendor='" + VendorText.getText() + "' ,"
                    + "Periodicity='" + PeriodicityCombo.getSelectedItem().toString() + "' ,"
                    + "Edition='" + EditionText.getText() + "' ,"
                    + "Volume='" + VolumeText.getText() + "' ,"
                    + "Number='" + NumberText.getText() + "' ,"
                    + "ReceiptDate='" + ReceiptDateText.getText() + "' "
                    + "where ID='" + ID + "';";
    }

    private String AddQuery(){
        return "Insert into " + Type + " (ID,Title,PublisherID,Vendor,Periodicity,Edition,Volume,Number,ReceiptDate) "
                + "values (?,?,?,?,?,?,?,?,?);";
    }
    
    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql;
            if( Button.getText().equals("EDIT") ){
                sql = EditQuery();
                pst = conn.prepareStatement(sql);
            }
            else if( Button.getText().equals("ADD") ){
                sql = AddQuery();
                pst = conn.prepareStatement(sql);
                pst.setString( 1, IDText.getText() );
                pst.setString( 2, TitleText.getText() );
                pst.setString( 3, PublisherCombo.getSelectedItem().toString() );
                pst.setString( 4, VendorText.getText() );
                pst.setString( 5, PeriodicityCombo.getSelectedItem().toString() );
                pst.setString( 6, EditionText.getText() );
                pst.setString( 7, VolumeText.getText() );
                pst.setString( 8, NumberText.getText() );
                pst.setString( 9, ReceiptDateText.getText() );
            }

            pst.execute();
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
        close();
    }//GEN-LAST:event_ButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JournalMagazine( ID,Command,Type ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel Edition;
    private javax.swing.JTextField EditionText;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JLabel Number;
    private javax.swing.JTextField NumberText;
    private javax.swing.JLabel Periodicity;
    private javax.swing.JComboBox PeriodicityCombo;
    private javax.swing.JLabel Publisher;
    private javax.swing.JComboBox PublisherCombo;
    private javax.swing.JLabel ReceiptDate;
    private javax.swing.JTextField ReceiptDateText;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TitleText;
    private javax.swing.JLabel Vendor;
    private javax.swing.JTextField VendorText;
    private javax.swing.JLabel Volume;
    private javax.swing.JTextField VolumeText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
