/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LUV
 */
public class JournalMagazine extends javax.swing.JFrame {

    private static String ID;
    private static String Command;
    private static String Type;
    private static String sub_id;
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    /**
     * Creates new form JournalMagazine
     * @param id
     * @param command
     * @param type
     */
    public JournalMagazine( String id , String command , String type ) {
        ID = id;
        Command = command;
        Type = type;
        initComponents();
        conn = FunctionClasses.DataBaseConnection.ConnectDB();
        if( Command.equals("EDIT") ){
            Button.setText("SAVE");
            DisplayData();
        }
        else if( Command.equals("ADD") )
            Button.setText("ADD");
        fillCombos();
    }

    private void fillCombos(){
        try{
            String sql = "select sub_name from subjects;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            cbSubjects.removeAllItems();
            while( rs.next() )
                cbSubjects.addItem(rs.getString("sub_name"));
            
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    private void DisplayData(){
        try{
            String sql = " select * from bibliography,subjects," + Type + " where acc_id = '" + ID + "' and bibliography.acc_id = "+ Type +".acc_id and bibliography.sub_id = subjects.sub_id ;";
            pst = conn.prepareStatement( sql );
            rs = pst.executeQuery();
            
            if( rs.next() ){
                IDText.setText( rs.getString("bibliography.acc_id") );
                TitleText.setText( rs.getString("bibname") );
                VendorText.setText( rs.getString("author") );
                cbSubjects.setSelectedItem( rs.getString("sub_name") );
                ReceiptDateText.setText( rs.getString("doa") );
                if( Type.equals("book")){
                    tvIssue.setText( rs.getString("issued") );
                    tvIssue.setEnabled(false);
                } else{
                    tvIssue.setText( rs.getString("issue_no") );
                    tvIssue.setEnabled(true);
                }
            }
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();    
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
    }
    
    public void close(){
        WindowEvent winClosingEvent = new WindowEvent( this , WindowEvent.WINDOW_CLOSING );
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ReceiptDateText = new javax.swing.JTextField();
        IDLabel = new javax.swing.JLabel();
        Vendor = new javax.swing.JLabel();
        VendorText = new javax.swing.JTextField();
        Publisher = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        ReceiptDate = new javax.swing.JLabel();
        TitleText = new javax.swing.JTextField();
        vSubject = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        cbSubjects = new javax.swing.JComboBox();
        tvPublisher = new javax.swing.JTextField();
        vIssue = new javax.swing.JLabel();
        tvIssue = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Button = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ReceiptDateText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ReceiptDateText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        IDLabel.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        IDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel.setText("ID");

        Vendor.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Vendor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vendor.setText("AUTHOR");

        VendorText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        VendorText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Publisher.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Publisher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Publisher.setText("PUBLISHER");

        Title.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("TITLE");

        ReceiptDate.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        ReceiptDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReceiptDate.setText("DATE");

        TitleText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        TitleText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vSubject.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        vSubject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vSubject.setText("SUBJECT");

        IDText.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        IDText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cbSubjects.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        tvPublisher.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvPublisher.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vIssue.setFont(new java.awt.Font("Yu Mincho", 1, 18)); // NOI18N
        vIssue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vIssue.setText("ISSUE");

        tvIssue.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tvIssue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vIssue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReceiptDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Vendor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Publisher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(vSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReceiptDateText)
                            .addComponent(VendorText)
                            .addComponent(IDText)
                            .addComponent(TitleText)
                            .addComponent(cbSubjects, 0, 500, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tvPublisher, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tvIssue))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Publisher, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvPublisher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vendor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VendorText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReceiptDate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceiptDateText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvIssue))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        CancelButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String EditQuery(){
        return "update bibliography set acc_id='" + IDText.getText() + "' ,"
                    + "bibname='" + TitleText.getText() + "' ,"
                    + "publication='" + tvPublisher.getText() + "' ,"
                    + "author='" + VendorText.getText() + "' ,"
                    + "sub_id='" + sub_id + "' ,"
                    + "doa='" + ReceiptDateText.getText() + "' "
                    + "where acc_id='" + ID + "';";
    }

    private String AddQuery(){
        return "Insert into " + Type + " (acc_id,bibname,publication,author,sub_id,doa) "
                + "values (?,?,?,?,?,?,?,?,?);";
    }
    
    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql = " select sub_id from subjects where sub_name = '" + cbSubjects.getSelectedItem().toString() + "';";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if( rs.next() )
                sub_id = rs.getString("sub_id");

            if( Button.getText().equals("EDIT") ){
                sql = EditQuery();
                pst = conn.prepareStatement(sql);
            } else if( Button.getText().equals("ADD") ){
                sql = AddQuery();
                pst = conn.prepareStatement(sql);
                pst.setString( 1, IDText.getText() );
                pst.setString( 2, TitleText.getText() );
                pst.setString( 3, tvPublisher.getText() );
                pst.setString( 4, VendorText.getText() );
                pst.setString( 5, sub_id );
                pst.setString( 6, ReceiptDateText.getText() );
            }

            pst.execute();
        }catch( Exception e ){
            JOptionPane.showMessageDialog( null, e );
        }finally{
            try{
                rs.close();
                pst.close();
            }catch( Exception e ){
                JOptionPane.showMessageDialog( null, e );
            }
        }
        close();
    }//GEN-LAST:event_ButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_CancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JournalMagazine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JournalMagazine( ID,Command,Type ).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDText;
    private javax.swing.JLabel Publisher;
    private javax.swing.JLabel ReceiptDate;
    private javax.swing.JTextField ReceiptDateText;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TitleText;
    private javax.swing.JLabel Vendor;
    private javax.swing.JTextField VendorText;
    private javax.swing.JComboBox cbSubjects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tvIssue;
    private javax.swing.JTextField tvPublisher;
    private javax.swing.JLabel vIssue;
    private javax.swing.JLabel vSubject;
    // End of variables declaration//GEN-END:variables
}
