/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisibleFrames;

import javax.swing.JFrame;

/**
 *
 * @author LUV
 */
public class studentHome extends javax.swing.JFrame {

    /**
     * Creates new form studentHome
     */
    private static String userid;
    
    public studentHome(String userid) {
        this.userid = userid;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        detailsButton = new javax.swing.JButton();
        btInstitute = new javax.swing.JButton();
        LibraryButton = new javax.swing.JButton();
        NoticeButton = new javax.swing.JButton();
        TaskButton = new javax.swing.JButton();
        ReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(0, 0, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        detailsButton.setBackground(new java.awt.Color(0, 0, 102));
        detailsButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        detailsButton.setForeground(new java.awt.Color(255, 255, 255));
        detailsButton.setText("DETAILS");
        detailsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        detailsButton.setFocusable(false);
        detailsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detailsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        btInstitute.setBackground(new java.awt.Color(0, 0, 102));
        btInstitute.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btInstitute.setForeground(new java.awt.Color(255, 255, 255));
        btInstitute.setText("INSTITUTE");
        btInstitute.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btInstitute.setFocusable(false);
        btInstitute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btInstitute.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btInstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInstituteActionPerformed(evt);
            }
        });

        LibraryButton.setBackground(new java.awt.Color(0, 0, 102));
        LibraryButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        LibraryButton.setForeground(new java.awt.Color(255, 255, 255));
        LibraryButton.setText("LIBRARY");
        LibraryButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LibraryButton.setFocusable(false);
        LibraryButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LibraryButton.setPreferredSize(new java.awt.Dimension(135, 39));
        LibraryButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        LibraryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryButtonActionPerformed(evt);
            }
        });

        NoticeButton.setBackground(new java.awt.Color(0, 0, 102));
        NoticeButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        NoticeButton.setForeground(new java.awt.Color(255, 255, 255));
        NoticeButton.setText("NOTICES");
        NoticeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NoticeButton.setEnabled(false);
        NoticeButton.setFocusable(false);
        NoticeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        NoticeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        NoticeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoticeButtonActionPerformed(evt);
            }
        });

        TaskButton.setBackground(new java.awt.Color(0, 0, 102));
        TaskButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        TaskButton.setForeground(new java.awt.Color(255, 255, 255));
        TaskButton.setText("TASKS");
        TaskButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TaskButton.setEnabled(false);
        TaskButton.setFocusable(false);
        TaskButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        TaskButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        TaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaskButtonActionPerformed(evt);
            }
        });

        ReportButton.setBackground(new java.awt.Color(0, 0, 102));
        ReportButton.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        ReportButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportButton.setText("REPORT");
        ReportButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReportButton.setFocusable(false);
        ReportButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReportButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(LibraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(detailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btInstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(ReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(NoticeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btInstitute, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(detailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LibraryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(TaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NoticeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        // TODO add your handling code here:
        Details frame = new Details( userid );
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void btInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInstituteActionPerformed
        // TODO add your handling code here:
        InstituteDetails frame = new InstituteDetails();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_btInstituteActionPerformed

    private void LibraryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryButtonActionPerformed
        // TODO add your handling code here:
        librarianHome frame = new librarianHome( "student",userid );
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_LibraryButtonActionPerformed

    private void NoticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoticeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NoticeButtonActionPerformed

    private void TaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaskButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TaskButtonActionPerformed

    private void ReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButtonActionPerformed
        // TODO add your handling code here:
        ComplaintBox frame = new ComplaintBox(userid);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_ReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentHome(userid).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LibraryButton;
    private javax.swing.JButton NoticeButton;
    private javax.swing.JButton ReportButton;
    private javax.swing.JButton TaskButton;
    private javax.swing.JButton btInstitute;
    private javax.swing.JButton detailsButton;
    private javax.swing.JPanel jPanel10;
    // End of variables declaration//GEN-END:variables
}
